# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef580172d84325c33f275a2a59061934a8faed4d30614f20f0f5d845c7ab908f13630b471cfc4db2201d1aafca8d53a2e5affe5e403c1ba9870b5d4914d03666

test:
  secret_key_base: 49020d53be88b30d2daa54fd6314ba1e5c699dd35ef1c0086b91fc0d913f6e4dda7cef176804d24661beeeaa1ef2e0f4073c0ef2db34d48036a89d6c76af45ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
